### PR TITLE
Update 66973391-036-00bStrongBot-Golaxy 9D.sgf

### PR DESCRIPTION
**Pull request by changcheng22023**
If we change komi to 6.5, won't it be better

### CODE REVIEW

**Comment by changcheng967** [comment]
> If we change komi to 6.5, won't it be better

I'm actually not sure

**Comment by changcheng967** [comment]
but this can not be proven, you can't change the original

**Comment by changchengdouletmedia** [comment]
I don't know if this is gonna work

**Comment by changchengdouletmedia** [comment]
https://online-go.com/game/66973552

**Comment by changchengdouletmedia** [comment]
testing

**Comment by changchengdouletmedia** [comment]
if works, will be closed but add a new commits

**Comment by changchengdouletmedia** [comment]
It's working out in a lovely way

**Comment by changchengdouletmedia** [comment]
3.0

**Comment by changcheng967** [comment]
> 3.0

The leading is pretty big

**Comment by changcheng22023** [comment]
638982db92418bd900c191f1acb63fd25280ec4b

maybe try 5.5?

**Comment by changcheng967** [comment]
I don't think it will make any diffrece because us 50ka and opponent 100k? impossiable, might be using opencl again

**Comment by changcheng967** [comment]
https://online-go.com/game/66973637

trying

**Comment by changchengdouletmedia** [comment]
https://github.com/changchengdouletmedia/OGS-Doulet-Media/pull/8

**Comment by changchengdouletmedia** [comment]
worked

**Pull request merged**
